name: Scheduled Workflow

on:
  schedule:
    - cron: '*/10 * * * *'    # Toutes les 10 minutes
    - cron: '0 0 1 * *'       # Le premier jour de chaque mois

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
